export default {
    API_URL_LOGIN: process.env.REACT_APP_API_URL_LOGIN, 
    API_URL_EXPENSES: process.env.REACT_APP_API_URL_EXPENSES, 
    API_URL_SERVICE_PROVIDERS: process.env.REACT_APP_API_URL_SERVICE_PROVIDERS, 
    APP_API_KEY: process.env.REACT_APP_API_KEY
}